In [ ]:
import numpy as np
import gym


In [ ]:
#Building the environment
env = gym.make('FrozenLake-v1')


/usr/local/lib/python3.9/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.9/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
#Defining the different parameters
epsilon = 0.9
total_episodes = 10000
max_steps = 100
alpha = 0.85
gamma = 0.95

#Initializing the Q-matrix
Q = np.zeros((env.observation_space.n, env.action_space.n))


In [ ]:
#Function to choose the next action
def choose_action(state):
	action=0
	if np.random.uniform(0, 1) < epsilon:
		action = env.action_space.sample()
	else:
		action = np.argmax(Q[state, :])
	return action

#Function to learn the Q-value
def update(state, state2, reward, action, action2):
	predict = Q[state, action]
	target = reward + gamma * Q[state2, action2]
	Q[state, action] = Q[state, action] + alpha * (target - predict)


In [ ]:
#Initializing the reward
reward=0

# Starting the SARSA learning
for episode in range(total_episodes):
	t = 0
	state1 = env.reset()
	action1 = choose_action(state1)

	while t < max_steps:
		#Visualizing the training
		#env.render()
		
		#Getting the next state
		state2, reward, done, info = env.step(action1)

		#Choosing the next action
		action2 = choose_action(state2)
		
		#Learning the Q-value
		update(state1, state2, reward, action1, action2)

		state1 = state2
		action1 = action2
		
		#Updating the respective vaLues
		t += 1
		reward += 1
		
		#If at the end of learning process
		if done:
			break


In [ ]:
#Evaluating the performance
print ("Performance : ", reward/total_episodes)

#Visualizing the Q-matrix
print(Q)


Performance :  0.0001
[[7.95389839e-04 1.25723391e-03 1.29172745e-05 4.09553819e-04]
 [2.13448087e-03 2.52746677e-03 8.91617004e-04 1.69993677e-03]
 [2.34997262e-03 6.32785832e-04 3.07591973e-03 2.52620491e-03]
 [5.13500776e-04 3.70320781e-04 2.85944982e-05 5.08817122e-04]
 [2.09021009e-01 3.23157829e-03 3.84705568e-02 4.57103456e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.03352679e-04 8.56844545e-02 8.70989789e-03 8.59496491e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.71408662e-02 9.40489613e-03 7.13654991e-03 5.41660416e-03]
 [4.60354872e-02 6.94071970e-02 9.75564269e-03 9.20430897e-07]
 [1.66303640e-03 1.95476126e-03 4.15020305e-02 4.61279488e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.86491779e-02 4.19860994e-02 8.00700176e-01 1.27468211e-02]
 [4.47229344e-02 1.42086008e-02 2.29653724e-01 1.56085570e-01]
 [0.00000000e+00 0.00000000e+00 0